name: Snyk Image Scan

on: push

jobs:
  snyk:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: docker build -t local/image .
    - name: Snyk vulnerability check
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: local/image
        args: --file=Dockerfile
    - name: Upload result
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif