name: Snyk example
on: push
jobs:
  security:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
        continue-on-error: true
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest
      - name: Snyk monitor
        run: snyk container test localbuild/testimage:latest --file=Dockerfile --exclude-base-image-vulns
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}